import * as stylex from '@stylexjs/stylex'
import { marigoldColors } from '../app/customStyles/marigoldColors.stylex'
import { fonts } from '@derekjwilliams/stylextras-open-props-pr/fonts.stylex'
import { sizes } from '@derekjwilliams/stylextras-open-props-pr/sizes.stylex'
import { borders } from '@derekjwilliams/stylextras-open-props-pr/borders.stylex'

const commonLinkProperties = {
  color: marigoldColors.textLinkButton,
  textDecoration: 'none',
  fontWeight: fonts.weight5,
  ':hover': {
    color: marigoldColors.textAccent,
    textDecoration: 'underline',
  },
  transition: 'color 0.15s ease',
}

export const styles = stylex.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  tableContainer: {
    width: '100%',
    maxWidth: '100%',
    overflowX: 'auto',
    position: 'relative',
    backgroundColor: marigoldColors.backgroundCard,
    boxSizing: 'border-box',
  },
  table: {
    width: '100%',
    minWidth: '800px',
    borderCollapse: 'collapse',
    tableLayout: 'auto',
  },
  column: {
    textAlign: 'left',
    paddingRight: sizes.spacing2,
  },
  costColumn: {
    width: '110px',
    minWidth: '110px',
    maxWidth: '110px',
    textAlign: 'right',
    paddingRight: sizes.spacing2,
  },
  typeColumn: {
    width: '140px',
    minWidth: '140px',
    maxWidth: '140px',
  },
  dateTimeColumn: {
    width: '120px',
    minWidth: '120px',
    maxWidth: '100px',
  },
  statusColumn: {
    width: '150px',
    minWidth: '150px',
    maxWidth: '150px',
  },
  technicianColumn: {
    minWidth: '150px',
    maxWidth: '200px',
  },
  locationColumn: {
    minWidth: '150px',
    maxWidth: '200px',
  },
  descriptionColumn: {
    minWidth: '200px',
  },
  headerCell: {
    paddingTop: sizes.spacing3,
    paddingBottom: sizes.spacing3,
    paddingLeft: sizes.spacing2,
    paddingRight: sizes.spacing2,
    textAlign: 'left',
    fontWeight: fonts.weight6,
    fontSize: fonts.size1,
    color: marigoldColors.tableHeaderText,
    backgroundColor: marigoldColors.tableHeaderBackground,
    cursor: 'pointer',
    userSelect: 'none',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    whiteSpace: 'nowrap',
    ':hover': {
      backgroundColor: marigoldColors.tableRowHover,
    },
    transition: 'background-color 0.15s ease',
  },
  row: {
    backgroundColor: marigoldColors.backgroundCard,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: marigoldColors.borderSubtle,
    ':hover': {
      backgroundColor: marigoldColors.tableRowHover,
    },
    transition: 'background-color 0.15s ease',
  },
  cell: {
    padding: sizes.spacing2,
    color: marigoldColors.textPrimary,
    fontSize: fonts.size1,
    verticalAlign: 'top',
    lineHeight: 1.4,
    maxWidth: '200px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  paginationControls: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: sizes.spacing2,
    marginTop: sizes.spacing3,
    marginBottom: sizes.spacing3,
    padding: sizes.spacing3,
    backgroundColor: marigoldColors.backgroundCard,
    flexWrap: 'wrap',
    boxSizing: 'border-box',
    '@media (max-width: 768px)': {
      flexDirection: 'column',
      gap: sizes.spacing2,
    },
  },
  headerCellNonSortable: {
    cursor: 'default',
    ':hover': {
      backgroundColor: marigoldColors.tableHeaderBackground,
    },
  },
  sortIndicator: {
    marginLeft: sizes.spacing1,
    color: marigoldColors.textAccent,
    display: 'inline-flex',
    alignItems: 'center',
  },
  descriptionLink: {
    ...commonLinkProperties,
  },
  locationLink: {
    ...commonLinkProperties,
  },
  techniciansList: {
    display: 'flex',
    flexDirection: 'column',
    gap: sizes.spacing1,
  },
  technicianLink: {
    color: marigoldColors.textLinkButton,
    textDecoration: 'none',
    fontSize: fonts.size1,
    ':hover': {
      color: marigoldColors.textAccent,
      textDecoration: 'underline',
    },
    transition: 'color 0.15s ease',
  },
  unassignedText: {
    color: marigoldColors.textMuted,
    fontStyle: 'italic',
    fontSize: fonts.size1,
  },
  emptyState: {
    paddingTop: sizes.spacing6,
    paddingBottom: sizes.spacing6,
    paddingLeft: sizes.spacing4,
    paddingRight: sizes.spacing4,
    textAlign: 'center',
    color: marigoldColors.textMuted,
    fontSize: fonts.size3,
    fontWeight: fonts.weight5,
  },
  footer: {
    padding: [sizes.spacing3, sizes.spacing4].join(' '),
    textAlign: 'right',
    color: marigoldColors.textMuted,
    backgroundColor: marigoldColors.backgroundCard,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    color: marigoldColors.textPrimary,
    fontSize: fonts.size3,
    fontWeight: fonts.weight6,
    borderRadius: borders.radius2,
  },
  paginationNavigation: {
    display: 'flex',
    alignItems: 'center',
    gap: sizes.spacing3,
  },
  paginationButton: {
    borderColor: marigoldColors.borderSubtle,
    paddingTop: sizes.spacing2,
    paddingBottom: sizes.spacing2,
    paddingLeft: sizes.spacing4,
    paddingRight: sizes.spacing4,
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: borders.radius1,
    backgroundColor: marigoldColors.backgroundButton,
    color: marigoldColors.foregroundButton,
    cursor: 'pointer',
    fontWeight: fonts.weight5,
    fontSize: fonts.size1,
    transition: 'all 0.2s ease',
    ':hover': {
      backgroundColor: marigoldColors.backgroundHoverButton,
      borderColor: marigoldColors.textAccent,
    },
    ':disabled': {
      opacity: 0.5,
      cursor: 'not-allowed',
      backgroundColor: marigoldColors.backgroundButton,
      ':hover': {
        backgroundColor: marigoldColors.backgroundButton,
        borderColor: marigoldColors.borderSubtle,
      },
    },
  },
  pageInfo: {
    margin: '0 ' + sizes.spacing2,
    color: marigoldColors.textPrimary,
    fontSize: fonts.size1,
    fontWeight: fonts.weight5,
    whiteSpace: 'nowrap',
  },
  pageSizeSelect: {
    paddingTop: sizes.spacing2,
    paddingBottom: sizes.spacing2,
    paddingLeft: sizes.spacing3,
    paddingRight: sizes.spacing3,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: marigoldColors.borderSubtle,
    borderRadius: borders.radius1,
    backgroundColor: marigoldColors.selectBackground,
    color: marigoldColors.selectInputColor,
    fontSize: fonts.size1,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    ':hover': {
      borderColor: marigoldColors.textAccent,
    },
  },
  costCell: {
    textAlign: 'right',
    fontWeight: fonts.weight5,
    fontFamily: 'monospace',
    paddingRight: sizes.spacing8,
  },
  archivedCheckboxContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: sizes.spacing2,
    color: marigoldColors.textPrimary,
    fontSize: fonts.size1,
  },
  archivedCheckbox: {
    width: 16,
    height: 16,
    cursor: 'pointer',
  },
  archivedLabel: {
    cursor: 'pointer',
    fontWeight: fonts.weight5,
    color: marigoldColors.textPrimary,
  },
  statusBadge: {
    display: 'inline-block',
    paddingTop: sizes.spacing1,
    paddingBottom: sizes.spacing1,
    paddingLeft: sizes.spacing2,
    paddingRight: sizes.spacing2,
    borderRadius: borders.radius1,
    fontSize: fonts.size0,
    fontWeight: fonts.weight6,
    textTransform: 'uppercase',
    letterSpacing: '0.025em',
    color: '#ffffff',
    minWidth: '60px',
    textAlign: 'center',
  },
  statusOpen: {
    backgroundColor: marigoldColors.statusOpen,
  },
  statusClosed: {
    backgroundColor: marigoldColors.statusClosed,
  },
  statusInProgress: {
    backgroundColor: marigoldColors.statusInProgress,
  },
})
