export const serviceTypes = new Map<string, any>()

serviceTypes.set('Safety', { displayName: 'Safety', image: 'safety.svg' })
serviceTypes.set('Hvac', { displayName: 'Heating and Cooling', image: 'heating_and_cooling.svg' })
serviceTypes.set('Pests', { displayName: 'Pests', image: 'pests.svg' })
serviceTypes.set('Safety', { displayName: 'Safety', image: 'safety.svg' })
serviceTypes.set('FloorsWallsDoorsWindows', { displayName: 'Walls, Doors, Windows', image: 'doors_and_windows.svg' })
serviceTypes.set('Electrical', { displayName: 'Electrical', image: 'electrical.svg' })
serviceTypes.set('Broadband', { displayName: 'Broadband', image: 'broadband.svg' })
serviceTypes.set('Laundry', { displayName: 'Laundry', image: 'laundry.svg' })
serviceTypes.set('Locks', { displayName: 'Safety', image: 'lock.svg' })
serviceTypes.set('Dishwasher', { displayName: 'Dishwasher', image: 'dishwasher.svg' })
serviceTypes.set('Refrigerator', { displayName: 'Refrigerator', image: 'refrigerator.svg' })
serviceTypes.set('KitchenPlumbing', { displayName: 'Kitchen Plumbing', image: 'kitchen_under_plumbing.svg' })
serviceTypes.set('BathroomPlumbing', { displayName: 'Bathroom Plumbing', image: 'bathroom_plumbing.svg' })
serviceTypes.set('WaterHeater', { displayName: 'Water Heater', image: 'water_heater.svg' })
serviceTypes.set('RoofGutters', { displayName: 'Roof and Gutters', image: 'roof.svg' })
serviceTypes.set('TreesLawnLandscaping', { displayName: 'Lawn and Landscaping', image: 'tree.svg' })
